### PR TITLE
Update structure

### PR DESCRIPTION
**Pull request by supernord**
Hi @vmurigneu 
I've made some suggestions here for the structure of the workflow guide.

### CODE REVIEW

**Comment by supernord** [comment]
It looks like you need to add in affiliation information for `QCIF` as well. 
This can be added to https://github.com/vmurigneu/shotgun_howto_ga_workflows/blob/main/_data/affiliations.yml

```
- name: QCIF
  image_url: [add QCIF logo location here if needed]
  expose: true
  type: infrastructure
  url: https://www.qcif.edu.au/
```

**Comment by vmurigneu** [comment]
hi @supernord 
Is it an error with the Elixir theme?
      Remote Theme: Using theme elixir-belgium/elixir-toolkit-theme
  Liquid Exception: undefined method `sort' for "QCIF":String input.sort ^^^^^ in /_layouts/page.html

**Comment by supernord** [comment]
Hi @vmurigneu 
It seems that it is expecting to find metadata for `QCIF` in this file: https://github.com/vmurigneu/shotgun_howto_ga_workflows/blob/main/_data/affiliations.yml
It would be expecting this because you have added `affiliation: QCIF` to one of the pages in your guide

**Review by vmurigneu — COMMENTED** [review]
not accepting the modification for the pages file

**Pull request merged**
